spring:
  profiles:
    active:
      - cat
      - EN
      - prod
jon:
  username: YmlUsername
  password: YmlPAssword
  jdbcurl: YmlJdbcurl

---

spring:
  profiles: prod
jon:
  username: YmlProdUsername
  password: YmlProdPAssword
  jdbcurl: YmlProdJdbcurl